# Generated by Django 5.1.2 on 2024-11-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='descripcion',
            field=models.TextField(default='Sin descripción'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='animal',
            name='habitat',
            field=models.CharField(max_length=100),
        ),
    ]
